---
# ------------------------------------------------------------------------------
# Velero
#
#
# Velero is an open source backup and migration tool for Kubernetes.
# See more about Velero at:
#
# * https://velero.io/
# * https://github.com/vmware-tanzu/velero
# * https://github.com/vmware-tanzu/helm-charts
#
#
# Implementation
#
#
# Our implementation of Velero currently supports S3 backends for storage, and by default if no configuration overrides are
# provided to point it at a backend other than the default, we will create and manage a distributed Minio (https://min.io/)
# cluster which uses the default storage class for the cluster to maintain the backups.
#
#
# WARNING: using the default (fallback) backend is for testing purposes only and should not be used in production.
# ------------------------------------------------------------------------------
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: velero
  labels:
    kubeaddons.mesosphere.io/name: velero
    # TODO: we're temporarily supporting dependency on an existing default storage class
    # on the cluster, this hack will trigger re-queue on Addons until one exists.
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.3.0-1"
    values.chart.helm.kubeaddons.mesosphere.io/velero: "https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.9.1/charts/velero/values.yaml"
spec:
  namespace: velero
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 2.9.1
