---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: kube2iam
  labels:
    kubeaddons.mesosphere.io/name: kube2iam
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.10.7-1"
    values.chart.helm.kubeaddons.mesosphere.io/kube2iam: "https://raw.githubusercontent.com/helm/charts/master/stable/kube2iam/values.yaml"
spec:
  namespace: kube-system
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
  chartReference:
    chart: kube2iam
    repo: https://kubernetes-charts.storage.googleapis.com
    version: 2.1.0